# Generated by Django 6.0.3 on 2026-03-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('original_name', models.CharField(max_length=255)),
                ('size', models.BigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
