# Generated by Django 6.0.3 on 2026-03-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_processed',
            field=models.BooleanField(db_comment='Đã được xử lý xong chưa', default=False),
        ),
    ]
